messages = [
    # IMPORTANT (1)
    ("urgent: submit assignment before 11 pm", 1),
    ("meeting at 3 pm in lab", 1),
    ("deadline extended till tomorrow", 1),
    ("project review at 5 pm", 1),
    ("exam schedule released check portal", 1),
    ("call me asap it's important", 1),
    ("team meeting rescheduled to 2 pm", 1),
    ("final submission tonight don't forget", 1),
    ("presentation slides needed by evening", 1),
    ("client call at 6 pm be ready", 1),
    ("important: bring documents tomorrow", 1),
    ("hackathon submission deadline approaching", 1),
    ("urgent update required on project", 1),
    ("faculty meeting tomorrow morning", 1),
    ("results declared check website", 1),
    ("payment due today", 1),
    ("lab evaluation happening today", 1),
    ("attendance shortage warning", 1),
    ("submit report before 5 pm", 1),
    ("interview scheduled tomorrow at 10", 1),
    ("important announcement check mail", 1),
    ("group discussion at 4 pm", 1),
    ("assignment deadline extended", 1),
    ("class test tomorrow prepare well", 1),
    ("important: venue changed", 1),
    ("final year project submission today", 1),
    ("urgent fix needed in code", 1),
    ("meeting link updated join on time", 1),
    ("deadline reminder submit asap", 1),
    ("important call from HR", 1),

    # NOT IMPORTANT (0)
    ("lol that was funny 😂", 0),
    ("what are you doing", 0),
    ("good morning", 0),
    ("good night", 0),
    ("let's go for lunch", 0),
    ("did you watch that movie", 0),
    ("haha nice one", 0),
    ("random meme 😂😂", 0),
    ("where are you", 0),
    ("come to canteen", 0),
    ("what's up", 0),
    ("bro listen to this song", 0),
    ("just chilling", 0),
    ("ok cool", 0),
    ("see you later", 0),
    ("nothing much", 0),
    ("free right now?", 0),
    ("let's hang out", 0),
    ("send notes please", 0),
    ("did you eat", 0),
    ("i am bored", 0),
    ("same here 😂", 0),
    ("brb", 0),
    ("hmm okay", 0),
    ("check this reel", 0),
    ("so sleepy", 0),
    ("any plans today", 0),
    ("just woke up", 0),
    ("going home", 0),
    ("talk later", 0),
]